"""таблица media

Revision ID: 166b3edfd2f8
Revises: 42b7ee65f28f
Create Date: 2023-05-18 14:19:55.540387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166b3edfd2f8'
down_revision = '42b7ee65f28f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('author', sa.Integer(), nullable=True),
                    sa.Column('UUID', sa.String(), nullable=False),
                    sa.Column('file', sa.LargeBinary(), nullable=False),
                    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
