"""поле file_name

Revision ID: 604152c2a972
Revises: 166b3edfd2f8
Create Date: 2023-05-26 11:03:14.507643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604152c2a972'
down_revision = '166b3edfd2f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('file_name', sa.String(), nullable=False))
    op.alter_column('media', 'author',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'user', ['UUID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('media', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('media', 'file_name')
    # ### end Alembic commands ###
